### PR TITLE
max line length of 80

### PR DESCRIPTION
**Pull request by paniclater**
Add max line length rule.

### CODE REVIEW

**Comment by sambev** [comment]
Yes please.

**Comment by redperk** [comment]
I'm fine with this.

**Comment by lukeschunk** [comment]
very for it. how'd you settle on 80?

**Comment by sambev** [comment]
@lukeschunk https://softwareengineering.stackexchange.com/a/148678.

When it really comes down to it, this story goes wayyyyy back.

**Comment by jtanner** [comment]
I feel like 80 is too short. What about 100?

**Comment by paniclater** [comment]
I'm fine with 100

**Comment by jtanner** [comment]
Whatever it ends up being I'm good with a line length limit 👍

**Comment by paniclater** [comment]
Will merge and implement as soon as I get a shipit.

**Comment by cerinman** [comment]
:shipit:

**Pull request merged**
