### PR TITLE
Add missing dependency from prior cleanup

### PR DESCRIPTION
**Pull request by jtanner**
I was overzealous in my previous commit and missed `eslint-plugin-react`. This adds it back in.

I also fixed a couple of deprecation warnings.

@lukeschunk

### CODE REVIEW

**Comment by lukeschunk** [comment]
:shipit:

**Comment by lukeschunk** [comment]
@jtanner do we want this merged in?

**Comment by jtanner** [comment]
@lukeschunk I forgot about this, thanks for the reminder. I merged in master and fixed the version so this needs another 🚢 🙏

**Comment by lukeschunk** [comment]
:shipit:

**Pull request merged**
