### PR TITLE
Adding new eslint rules (w/ minimal change to code)

### PR DESCRIPTION
**Pull request by scotttball**
## Easy to Implement Rules (w/ minimal change to code)
- [`react/require-render-return`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/require-render-return.md): When writing the `render` method in a component it could be easy to forgot to `return` the JSX content. This rule will warn you if the return statement is missing.
- [`react/jsx-pascal-case`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-pascal-case.md): Enforces coding style that user-defined JSX components are defined and referenced in PascalCase.
- [`react/jsx-space-before-closing`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-space-before-closing.md) : This rule checks if there is one or more spaces before the closing bracket of self-closing JSX elements.
- [`react/jsx-closing-bracket-location`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-closing-bracket-location.md) : Enforce the closing bracket location for JSX multiline elements.
- [`arrow-spacing`](http://eslint.org/docs/rules/arrow-spacing) : This rule normalize style of spacing before/after an arrow function’s arrow(`=>`).      `spacing: { before: true, after: true }`
- [`no-confusing-arrow`](http://eslint.org/docs/rules/no-confusing-arrow) : Arrow functions (`=>`) are similar in syntax to some comparison operators (`>`, `<`, `<=`, and `>=`). This rule warns against using the arrow function syntax in places where it could be confused with a comparison operator.

### CODE REVIEW

**Comment by lukeschunk** [comment]
Thanks for making a PR with all the links and well organized 🍪 

the only One I am a bit iffy about is the no-confusing arrow. But it seems like an edge case rule anyway

**Comment by paniclater** [comment]
I like the fat arrow rule because I think

```
var x = a => { return 1 ? 2 : 3; };
var x = (a) => { return 1 ? 2 : 3; };
```

reads much better than 

```
var x = a => 1 ? 2 : 3;
```

**Comment by lukeschunk** [comment]
👍  sounds good

**Comment by lukeschunk** [comment]
:shipit:

**Pull request merged**
