### PR TITLE
3.0 release: Upgrade all peer deps to latest versions

### PR DESCRIPTION
**Pull request by whiteinge**
This PR is messy and each commit is best read/reviewed individually.

### CODE REVIEW

**Comment by sambev** [comment]
This looks fine from a code standpoint. What do you think is the easiest way for me to test these kinds of breaking changes out?

**Comment by sambev** [comment]
Trying this out locally, I noticed some changes:

- We should remove `radix`. It is [no longer meaningful](https://eslint.org/docs/latest/rules/radix) in browsers we target
- We should remove `newline-after-var`. It is [deprecated](https://eslint.org/docs/latest/rules/newline-after-var) and useless anyway
- We should remove `max-nested-callback`. It is arbitrary and useless
- The new parser seems to catch a lot more react prop/state, which is great.

**Comment by whiteinge** [comment]
> What do you think is the easiest way for me to test these kinds of breaking changes out?

(We already talked about this on Slack but in case anyone else has the same question.)

1. Run `npm pack` which will generate a tarball in the repo directory.
2. Go to the repo you want to test it with and run `npm i /path/to/this/repo/eslint-config-mx-3.0.0.tgz`

**Comment by sambev** [comment]
I was able to get my project working well with the latest commits. LGTM. :shipit:

**Pull request merged**
